tello_driver:
  ros__parameters:
    # Topics
    image_topic_name: '/camera/image_raw'
    flight_data_topic_name: '/flight_data'
    velocity_command_topic_name: '/cmd_vel'
    land_topic_name: '/land'
    takeoff_topic_name: '/takeoff'
    flip_control_topic_name: '/flip'
    odom_topic_name: 'odom'
    imu_topic_name: 'imu'
    # Frame ids
    imu_frame_id: 'imu'
    odom_frame_id: 'odom'
    drone_frame_id: 'tello'
    auto_wifi_connection: false
    tello_ssid: 'tello10'
    tello_pw: ''
